// Fill out your copyright notice in the Description page of Project Settings.


#include "AWeekPlayerAnimInstance.h"

#include "KismetAnimationLibrary.h"
#include "../Data/AWeekPlayerAnimInfo.h"
#include "../Character/AWeekPlayerCharacter.h"
#include "../AWeekAssetManager.h"
#include "KismetAnimationLibrary.h"
#include "../Character/AWeekPlayerCharacter.h"

void UAWeekPlayerAnimInstance::NativeBeginPlay()
{
	Super::NativeBeginPlay();

	mOwner = Cast<AAWeekPlayerCharacter>(GetOwningActor());

	// 魹ｽﾖｴﾏｸ魹ｽ魹ｽﾌｼ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽﾌｺ魹ｽ 魹ｽ魹ｽﾃｼ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ
	if (!AnimInfoDT) return;

	// 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽﾌｺ魹ｽ魹ｽ魹ｽ RowMap魹ｽﾌｶ魹ｽ魹ｽ TMap魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽﾈｯ魹ｽ魹ｽ (Row魹ｽ魹ｽ ﾅｰ魹ｽ魹ｽ, 魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ)
	TMap<FName, uint8*> RowMap = AnimInfoDT->GetRowMap();
	for (auto& Row : RowMap)
	{
		FName RowKey = Row.Key;

		// uint8*(魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽﾌｺ魹ｽ Value魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽﾅｰ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ)魹ｽ魹ｽ FPlayerInfo魹ｽ魹ｽ ﾄｳ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ
		// Cast魹ｽ魹ｽ 魹ｽ𡵸ｮｾ魹ｽ ﾅｬ魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽﾌｶ魹ｽ魹ｽ, reinterperet_cast魹ｽ魹ｽ C++ ﾇ･魹ｽ魹ｽ ﾄｳ魹ｽ魹ｽﾆｮ 魹ｽﾔｼ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽﾃｼ魹ｽ魹ｽ 魹ｽ魹ｽﾈｯ魹ｽ魹ｽ魹ｽﾘｴ魹ｽ.
		FPlayerAnimInfo* RowData = reinterpret_cast<FPlayerAnimInfo*>(Row.Value);

		// 魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽﾈｿ魹ｽﾏｴﾙｸ魹ｽ AnimInstance魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽﾖｴ魹ｽ 魹ｽﾊｿ魹ｽ 魹ｽﾟｰ魹ｽ魹ｽ魹ｽ魹ｽﾘｴ魹ｽ.
		if (RowData)
		{
			mAnimMap.Add(RowKey, *RowData);
		}
	}

	// 魹ｽﾏｼ魹ｽ魹ｽ魹ｽ mAnimMap魹ｽ魹ｽ 魹ｽﾃｷ魹ｽ魹ｽﾌｾ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ(魹ｽ魹ｽ魹ｽ/魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ/魹ｽ魹ｽ魹ｽﾅｸ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ)魹ｽ魹ｽ 魹ｽ魹ｽﾅｸ魹ｽ魹ｽ魹ｽ魹ｽ FName魹ｽ魹ｽ ﾅｰ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ FPlayerAnimInfo魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽﾖｰ魹ｽ,
	// 魹ｽﾌｰﾅｸ魹ｽ 魹ｽﾖｴ魹ｽ魹ｽﾎｽ魹ｽ魹ｽﾏｽ魹ｽ魹ｽ魹ｽ 魹ｽﾖｴﾏｸ魹ｽ魹ｽﾌｼ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ, 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ蠖ｺ魹ｽ魹ｽ魹ｽﾌｽ魹ｽ, 魹ｽ魹ｽﾅｸ魹ｽﾖｷ魹ｽ 魹ｽﾒｴ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ.
	// 魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽﾛｽ魹ｽ 魹ｽﾃｷ魹ｽ魹ｽﾌｾ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ 魹ｽﾖｴﾏｸ魹ｽ魹ｽﾌｼ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽﾛｷ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽﾖｴ魹ｽ魹ｽﾎｽ魹ｽ魹ｽﾏｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽﾖｵ魹ｽ魹ｽ魹ｽ 魹ｽﾑｴ魹ｽ.
	// 魹ｽﾃｷ魹ｽ魹ｽﾌｾ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽﾂｸ魹ｽ ﾅｰ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ 魹ｽﾑｰ魹ｽ魹ｽﾖｸ魹ｽ 魹ｽﾖｴﾏｸ魹ｽ魹ｽﾌｼ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽ魹ｽﾌｵ魹ｽ 魹ｽ魹ｽ魹ｽ魹ｽ
	ChangeAnimOverride(mStatusKey);
	OnMontageEnded.AddDynamic(this, &UAWeekPlayerAnimInstance::MontageEnd);
}

void UAWeekPlayerAnimInstance::NativeInitializeAnimation()
{
	Super::NativeInitializeAnimation();
}

void UAWeekPlayerAnimInstance::NativeUpdateAnimation(float DeltaSeconds)
{
	Super::NativeUpdateAnimation(DeltaSeconds);
	if (!mOwner)
		return;
	AController* Controller = mOwner->GetController();
	if (!Controller) return;

	FVector Velocity = mOwner->GetVelocity();
	Velocity.Z = 0.0f;
	float Speed = Velocity.Size();
	Direction = UKismetAnimationLibrary::CalculateDirection(Velocity, mOwner->GetActorRotation());
	
	FRotator ControlRot = Controller->GetControlRotation();
	ControllerYaw = ControlRot.Yaw;
	ControllerPitch = ControlRot.Pitch;

	float LeftFoot = GetCurveValue(TEXT("Foot_L"));
	float RightFoot = GetCurveValue(TEXT("Foot_R"));

	if (LeftFoot > 0.9f && !bLeftFootTriggered)
	{
		mOwner->FootStepEffect(FName("foot_l_Socket"));
		bLeftFootTriggered = true;
	}
	else if (LeftFoot < 0.1f)
	{
		bLeftFootTriggered = false;
	}

	if (RightFoot > 0.9f && !bRightFootTriggered)
	{
		mOwner->FootStepEffect(FName("foot_r_Socket"));
		bRightFootTriggered = true;
	}
	else if (RightFoot < 0.1f)
	{
		bRightFootTriggered = false;
	}
}

UAnimSequence* UAWeekPlayerAnimInstance::FindAnimSequence(const FName& Name)
{
	TObjectPtr<UAnimSequence>* Sequence = mSequenceMap.Find(Name);

	if (!Sequence)
	{
		UE_LOG(LogTemp, Warning, TEXT("Sequence %s is not found"), *Name.ToString());
		return nullptr;
	}

	return Sequence->Get();
}

UBlendSpace* UAWeekPlayerAnimInstance::FindBlendSpace(const FName& Name)
{
	TObjectPtr<UBlendSpace>* BlendSpace = mBlendSpaceMap.Find(Name);

	if (!BlendSpace)
	{
		UE_LOG(LogTemp, Warning, TEXT("BS %s is not found"), *Name.ToString());
		return nullptr;
	}

	return BlendSpace->Get();
}

UAnimMontage* UAWeekPlayerAnimInstance::FindAnimMontage(const FName& Name)
{
	TObjectPtr<UAnimMontage>* Montage = mMontageMap.Find(Name);

	if (!Montage)
	{
		//UE_LOG(LogTemp, Warning, TEXT("Montage %s is not found"), *Name.ToString());
		return nullptr;
	}

	return Montage->Get();
}

void UAWeekPlayerAnimInstance::PlayMontageByName(FName Name, float PlayRate)
{
	UAnimMontage* Montage = FindAnimMontage(Name);
	if (Montage)
	{
		mOwner->EndFire();
		Montage_Play(Montage, PlayRate);
	}
}

void UAWeekPlayerAnimInstance::MontageEnd(UAnimMontage* Montage, bool bInterrupted)
{
	if (Montage == FindAnimMontage(TEXT("Vault")))
	{
		mOwner->VaultEnd();
	}

	if (Montage == FindAnimMontage(TEXT("Climb")))
	{
		mOwner->ClimbEnd();
	}

	if (Montage == FindAnimMontage(TEXT("Attack")))
	{
		mOwner->SetCombatBool(false);
	}
}

void UAWeekPlayerAnimInstance::AnimNotify_MeeleAttack()
{
	mOwner->AttackImpact();
}

void UAWeekPlayerAnimInstance::AnimNotify_Reload()
{
	mOwner->WeaponReload();
}

void UAWeekPlayerAnimInstance::AnimNotify_Heal()
{
	mOwner->Heal();
}

void UAWeekPlayerAnimInstance::AnimNotify_OnDie()
{
	mOwner->GameOver();
	Montage_Pause();
}

void UAWeekPlayerAnimInstance::AnimNotify_AN_FootPlant_Right()
{
	mOwner->FootStepEffect(FName("foot_r_Socket"));
}

void UAWeekPlayerAnimInstance::AnimNotify_AN_FootPlant_Left()
{
	mOwner->FootStepEffect(FName("foot_l_Socket"));
}
